// <auto-generated />
using AltLigMenajer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AltLigMenajer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260601161605_AddManagerTable")]
    partial class AddManagerTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AltLigMenajer.Models.Manager", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ManagedTeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ManagedTeamId")
                        .IsUnique();

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("AltLigMenajer.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormationRow")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsStarter")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSubstitute")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Ovr")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("TeamId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("AltLigMenajer.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Budget")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Points")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("AltLigMenajer.Models.Manager", b =>
                {
                    b.HasOne("AltLigMenajer.Models.Team", "ManagedTeam")
                        .WithOne("Manager")
                        .HasForeignKey("AltLigMenajer.Models.Manager", "ManagedTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ManagedTeam");
                });

            modelBuilder.Entity("AltLigMenajer.Models.Player", b =>
                {
                    b.HasOne("AltLigMenajer.Models.Team", "Team")
                        .WithMany("Players")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("AltLigMenajer.Models.Team", b =>
                {
                    b.Navigation("Manager");

                    b.Navigation("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
